마커 구현 및 지도 타입, 레이어 변경
SpartaFinalProjectAndroid/OFFROADER pull request #27
Opened 2024-02-27 13:16 UTC by rihan530

## 🛠 PR 체크리스트
다음 요구사항을 충족하는지 확인해주세요

- [x] 커밋메세지 규칙을 따릅니다.
- [x] 모든 함수에 주석을 달았습니다.

## ✨ PR 유형
어떤 변경사항이 있는지 모두 체크해 주세요

- [x] 기능구현
- [ ] 버그픽스
- [ ] 리팩토링
- [ ] 문서 변경
- [ ] 레이아웃

## 🧪 변경사항 작성
변경사항의 상세 정보를 작성해주세요.

-기능
마커 구현
- 산 마커 추가 및 아이콘, 캡션 변경
지도 타입 및 레이어 변경
- 위성지도로 변경
- 등산로 레이어 추가
- 지도 확대/축소 버튼 위치 변경

-설명
마커 구현 및 지도 타입, 레이어 변경

-참고

2024-02-27 13:28 UTC, eun-24k reviewed
지도 마킹 👍

2024-02-27 13:33 UTC, Box-o approved these changes
죠습니다!

2024-02-27 13:33 UTC, CodingVirus requested changes
산 이름 string에 저장해서 사용 해주세요!

2024-02-27 13:33 UTC, CodingVirus commented on app/src/main/java/com/mit/offroader/ui/fragment/map/SanMapFragment.kt
> +            captionText = "오대산"
산 이름 string에 저장해서 사용 해주세요!

2024-02-27 13:34 UTC, rihan530 commented on app/src/main/java/com/mit/offroader/ui/fragment/map/SanMapFragment.kt
> +        }
마커 이벤트때문에 이미지를 안보이게 하려면 작은 이미지를 아이콘으로 사용해야 비슷하게 구현할것 같아요

2024-02-27 13:35 UTC, Box-o commented on app/src/main/java/com/mit/offroader/ui/fragment/map/SanMapFragment.kt
> +            captionText = "오대산"
나중에 데이터베이스 사용하면 필요 없느니까 임시로 사용하신 것 같아요!!!!!!!

2024-02-28 01:22 UTC, CodingVirus approved these changes
승인합니다

2024-02-28 01:22 UTC, merged